from jvpm.parsing.constant_types import * #I'm only doing this because there will be a lot of these.
from unittest import TestCase
class TestConstants(TestCase):
    def test_constructors(self):
        c = Constant()
        self.assertEqual(type(c),Constant)
        c = ConstClass(1)
        self.assertEqual(type(c),ConstClass)
        self.assertEqual(c.name_index,1)
        c = ConstFieldRef(1,2)
        self.assertEqual(type(c),ConstFieldRef)
        self.assertEqual(c.class_index,1)
        self.assertEqual(c.name_and_type_index,2)
        c = ConstMethodRef(1,2)
        self.assertEqual(type(c),ConstMethodRef)
        self.assertEqual(c.class_index,1)
        self.assertEqual(c.name_and_type_index,2)
        c = ConstInterfaceMethodRef(1,2)
        self.assertEqual(type(c),ConstInterfaceMethodRef)
        self.assertEqual(c.class_index,1)
        self.assertEqual(c.name_and_type_index,2)
        c = ConstString(1)
        self.assertEqual(type(c),ConstString)
        self.assertEqual(c.string_index,1)
        c = ConstInteger(1)
        self.assertEqual(type(c),ConstInteger)
        self.assertEqual(c.chars,1)
        c = ConstFloat(1)
        self.assertEqual(type(c),ConstFloat)
        self.assertEqual(c.chars,1)
        c = ConstLong(1,2)
        self.assertEqual(type(c),ConstLong)
        self.assertEqual(c.high_bytes,1)
        self.assertEqual(c.low_bytes,2)
        c = ConstDouble(1,2)
        self.assertEqual(type(c),ConstDouble)
        self.assertEqual(c.high_bytes,1)
        self.assertEqual(c.low_bytes,2)
        c = ConstNameAndType(1,2)
        self.assertEqual(type(c),ConstNameAndType)
        self.assertEqual(c.name_index,1)
        self.assertEqual(c.descriptor_index,2)
        c = ConstUtf8(1,2)
        self.assertEqual(type(c),ConstUtf8)
        self.assertEqual(c.length,1)
        self.assertEqual(c.chars,2)
        c = ConstMethodHandle(1,2)
        self.assertEqual(type(c),ConstMethodHandle)
        self.assertEqual(c.reference_kind, 1)
        self.assertEqual(c.reference_index,2)
        c = ConstMethodType(1)
        self.assertEqual(type(c),ConstMethodType)
        self.assertEqual(c.descriptor_index,1)
        c = ConstInvokeDynamic(1,2)
        self.assertEqual(type(c),ConstInvokeDynamic)
        self.assertEqual(c.bootstrap_method_attr_index,1)
        self.assertEqual(c.name_and_type_index,2)
